azure2/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse

def hello(request):
    return HttpResponse('''
        <h1>Hello, <a href="http://facebook.com/askdjango/" target="_blank">AskDjango</a></h1>
        <h2><a href="/blog">Blog List</a></h2>
    ''')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$' , hello),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url

urlpatterns = [
	url(r'^$', 'blog.views.post_list'),
    url(r'^blog/$', 'blog.views.post_list', name='post_list'),
    url(r'^blog/(?P<pk>\d+)/$', 'blog.views.post_detail', name='post_detail'),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=40)
	content = models.TextField(max_length=1000)
	image = models.ImageField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.pk])

blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.

def post_list(request):
	post_list=Post.objects.all()
	return render(request, 'blog/post_list.html', {'post_list' : post_list,})


# def post_detail(request, pk):
#  	post_detail=Post.objects.get(pk=pk)
#  	return render(request, 'blog/post_detail.html', { 'post' : post,})

def post_detail(request, pk):
	post = Post.objects.get(pk=pk)
	return render(request, 'blog/post_detail.html',{'post' : post,})

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Ask Django Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
}

html {
  position: relative;
  min-height: 100%;
}

body {
  margin-bottom: 60px;
}

.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 60px;
  background-color: #f5f5f5;
}
</style>
</head>

<body>
<!--   <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.6&appId=1559430574382775";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> -->

  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Ask Django</a>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}

<div class="footer">
    <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
    </div>
</div>

</body>


</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<h1> {{ post.title }} </h1>

<hr>
{{ post.content }}
<hr>

<img src = "{{post.image.url}}"/>
<hr>

<div class="fb-comments" data-href="http://songazure2.azurewebsites.net" data-numposts="5">test2</div>

<a href="{% url "blog:post_list" %}"> 글 목록으로 </a>



<div id="fb-root"></div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
	<ul>
	{% for post in post_list %}
		<li>
			<a href="{% url 'blog:post_detail' post.pk %}">
			{{post.title}}
			</a>
		</li>
	{% endfor %}
	</ul>


{% endblock %}